-- APEX Database Schema for Supabase (PostgreSQL)
-- Run this in the Supabase SQL Editor: https://supabase.com/dashboard/project/_/sql

-- Cycle history table
CREATE TABLE IF NOT EXISTS cycles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL,
    node TEXT NOT NULL,
    guardian_decision TEXT,
    guardian_reason TEXT,
    guardian_detail TEXT,
    tx_hash TEXT,
    executed_protocol TEXT,
    actual_pnl REAL,
    execution_error TEXT,
    session_pnl REAL,
    veto_count INTEGER,
    approval_count INTEGER,
    cycle_number INTEGER,
    market_state JSONB DEFAULT '[]',
    intents JSONB DEFAULT '[]',
    veto_reason TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Reputation snapshots table
CREATE TABLE IF NOT EXISTS reputation_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id INTEGER NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    total_signals INTEGER,
    positive_signals INTEGER,
    negative_signals INTEGER,
    reputation_score REAL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_cycles_timestamp ON cycles(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_cycles_cycle_number ON cycles(cycle_number);
CREATE INDEX IF NOT EXISTS idx_rep_agent ON reputation_snapshots(agent_id);
CREATE INDEX IF NOT EXISTS idx_rep_timestamp ON reputation_snapshots(timestamp DESC);

-- Row Level Security (RLS) policies
-- Enable RLS on both tables
ALTER TABLE cycles ENABLE ROW LEVEL SECURITY;
ALTER TABLE reputation_snapshots ENABLE ROW LEVEL SECURITY;

-- Allow all authenticated operations (adjust for your auth setup)
-- For demo/hackathon: using anon key, so allow public read/write
CREATE POLICY "Allow public read on cycles" ON cycles FOR SELECT USING (true);
CREATE POLICY "Allow public insert on cycles" ON cycles FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read on reputation_snapshots" ON reputation_snapshots FOR SELECT USING (true);
CREATE POLICY "Allow public insert on reputation_snapshots" ON reputation_snapshots FOR INSERT WITH CHECK (true);
